/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':               '#121317',
        'surface':                  '#121317',
        'surface-dim':              '#121317',
        'surface-bright':           '#38393d',
        'surface-container-lowest': '#0d0e12',
        'surface-container-low':    '#1a1b20',
        'surface-container':        '#1e1f24',
        'surface-container-high':   '#292a2e',
        'surface-container-highest':'#343439',
        'surface-variant':          '#343439',
        'surface-tint':             '#c6bfff',
        'on-background':            '#e3e2e7',
        'on-surface':               '#e3e2e7',
        'on-surface-variant':       '#c8c4d7',
        'outline':                  '#928ea0',
        'outline-variant':          '#474554',
        'primary':                  '#c6bfff',
        'primary-container':        '#6c5ce7',
        'primary-fixed':            '#e4dfff',
        'primary-fixed-dim':        '#c6bfff',
        'on-primary':               '#2900a0',
        'on-primary-container':     '#faf6ff',
        'on-primary-fixed':         '#160066',
        'on-primary-fixed-variant': '#4029ba',
        'inverse-primary':          '#5847d2',
        'secondary':                '#46eae5',
        'secondary-container':      '#00cec9',
        'secondary-fixed':          '#5af9f3',
        'secondary-fixed-dim':      '#2edcd7',
        'on-secondary':             '#003735',
        'on-secondary-container':   '#005250',
        'on-secondary-fixed':       '#00201f',
        'on-secondary-fixed-variant':'#00504e',
        'tertiary':                 '#ffb77d',
        'tertiary-container':       '#ac5d00',
        'tertiary-fixed':           '#ffdcc3',
        'tertiary-fixed-dim':       '#ffb77d',
        'on-tertiary':              '#4d2600',
        'on-tertiary-container':    '#fff5f1',
        'on-tertiary-fixed':        '#2f1500',
        'on-tertiary-fixed-variant':'#6e3900',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
        'inverse-on-surface':       '#2f3035',
        'inverse-surface':          '#e3e2e7',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
